### ISSUE TITLE
Make cache key configurable

### ISSUE THREAD

**Issue by Mahoney** [win-t/gh-action-docker-state#3]
This is really nice - I did something very similar in bash - but I'd like to be able to define my own cache & restore keys so I could use it like this:
```yaml
steps:
  - uses: win-t/gh-action-docker-state@v1
    with:
      cache-key: docker1-${{ github.ref }}-${{ github.sha }}
      cache-restore-keys: |
            '**-${{ github.sha }}'
            docker1-${{ github.ref }}-
            docker1-
```

What do you think?
